-- NOTE: meant for mapping copilot to autocomplete with things other than Tab
-- vim.g.copilot_no_tab_map = true
-- vim.g.copilot_assume_mapped = true
-- vim.api.nvim_set_keymap("i", "<C-Space>", "copilot#Accept(\"<CR>\")",
--     { silent = true, expr = true })
