format = """
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$fill\
$line_break\
$character"""

right_format = """
$rust\
$conda\
$cmd_duration $jobs\
"""
# $cmd_duration $jobs $time\

[directory]
style = "blue"
read_only = " "
truncation_length = 4
truncate_to_repo = false

[character]
# # success_symbol = "[❯](purple)"
success_symbol = "[>](purple)"
error_symbol = "[x](red)"

# error_symbol = "[❯](red)"
# # vimcmd_symbol = "[❮](green)"
# vimcmd_symbol = "[nor](green)"
# # vimcmd_visual_symbol = "[❮](bold yellow)"
# vimcmd_visual_symbol = "[vis](bold yellow)"
# # vimcmd_replace_one_symbol = "[❮](bold purple)"
# vimcmd_replace_one_symbol = "[res](bold purple)"
# # vimcmd_replace_symbol = "[❮](bold purple)"
# vimcmd_replace_symbol = "[rep](bold purple)"

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "
style = "bright-black"

[jobs]
symbol = ""
style = "bold red"
number_threshold = 1
format = "[$symbol]($style)"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "cyan"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[git_metrics]
disabled = false

[cmd_duration]
format = "[$duration]($style)"
style = "yellow"

[memory_usage]
symbol = " "

[time]
disabled = false
style = "white"
format = "[$time]($style)"
