#!/usr/bin/env bash

preview () {
    if ! command -v bat > /dev/null; then
        echo "$1"
    fi
    bat --color "always" "$1"
} 

session=$(find ~/work ~/personal -mindepth 1 -maxdepth 2 -type d | fzf)

session_name=$(basename "$session" | tr . _)

if ! tmux has-session -t "$session_name" 2> /dev/null; then
    tmux new-session -s "$session_name" -c "$session" -d 
fi

tmux switch-client -t "$session_name"
